### PR TITLE
Adding support for Mopeka tank sensors

### PR DESCRIPTION
**Pull request by robsweet**

### CODE REVIEW

**Comment by robsweet** [comment]
Regarding testing, development was done with a Cerbo GX and Mopeka Pro LPG sensor. Mr.Ghostrider also helped test with Venus on a Raspberry Pi and said that looked fine. I don't have a Mopeka Pro sensor for water tanks so I can't test that but the logic to calculate the level is smart enough to know which kind of sensor is being reported so it can use the right coefficient values for the calculation.

**Comment by robsweet** [comment]
Changed MopekaSensorVersion to MopekaSensorTypeId at request of @mpvader to better align with Victron naming conventions.

**Comment by mansr** [comment]
Is the data format documented anywhere? I'm trying to make sense of the code, and that would be much easier if I knew what I was actually dealing with.

**Comment by robsweet** [comment]
> Is the data format documented anywhere? I'm trying to make sense of the code, and that would be much easier if I knew what I was actually dealing with.

I've got a doc about the format but I've been asked not to make it public. Please email me directly at Rob@LDG.net and I'll send it to you.

**Comment by mansr** [comment]
Some version of this was merged a long time ago.

**Pull request closed without merging**
